turbine:
  stream:
    port: 8887 # 这是turbine的端口即暴露监控数据的端口，跟server.port不同

spring:
  rabbitmq:
    host: rabbitmq-server
    port: 5673
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtualHost: /

# 这个是服务的端口
server:
  port: 8880








